// Turn the committed grpc-gateway OpenAPI spec (Swagger 2.0) into a typed client
// surface: convert 2.0 -> 3.0, then emit src/api/schema.d.ts. Run via
// `npm run gen:api`; CI verifies the output is committed and current.
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import converter from "swagger2openapi";
import openapiTS, { astToString } from "openapi-typescript";

const here = dirname(fileURLToPath(import.meta.url));
const specPath = resolve(here, "../../api/openapi/franz.swagger.json");
const outPath = resolve(here, "../src/api/schema.d.ts");

const swagger = JSON.parse(await readFile(specPath, "utf8"));
const { openapi } = await converter.convertObj(swagger, {
  patch: true,
  warnOnly: true,
});

const ast = await openapiTS(openapi, { alphabetize: true });
const banner = `// AUTO-GENERATED by \`npm run gen:api\` from ../api/openapi/franz.swagger.json.\n// Do not edit. Regenerate after any .proto change.\n\n`;
await writeFile(outPath, banner + astToString(ast));
console.log(`wrote ${outPath}`);
