// AUTO-GENERATED by `npm run gen:api` from ../api/openapi/franz.swagger.json.
// Do not edit. Regenerate after any .proto change.

export interface paths {
    "/v1/async-channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AsyncChannelService_ListAsyncChannels"];
        put?: never;
        post: operations["AsyncChannelService_CreateAsyncChannel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/async-channels/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AsyncChannelService_GetAsyncChannel"];
        put?: never;
        post?: never;
        delete: operations["AsyncChannelService_DeleteAsyncChannel"];
        options?: never;
        head?: never;
        patch: operations["AsyncChannelService_UpdateAsyncChannel"];
        trace?: never;
    };
    "/v1/async-channels/{name}:pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AsyncChannelService_PauseAsyncChannel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/async-channels/{name}:resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AsyncChannelService_ResumeAsyncChannel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/async-channels/{name}/access-policy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["AsyncChannelService_SetAccessPolicy"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/async-channels/{name}/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AsyncChannelService_ListChannelClients"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ClientService_ListClients"];
        put?: never;
        post: operations["ClientService_CreateClient"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/clients/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ClientService_GetClient"];
        put?: never;
        post?: never;
        delete: operations["ClientService_DeleteClient"];
        options?: never;
        head?: never;
        patch: operations["ClientService_UpdateClient"];
        trace?: never;
    };
    "/v1/clients/{name}/channel-access": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ClientService_ListClientChannelAccess"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/clients/{name}/consumer-group-observations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ClientService_ListConsumerGroupObservations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/clients/{name}/consumer-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ClientService_ListObservedConsumerGroups"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/governance/indicators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GovernanceService_ListIndicators"];
        put?: never;
        post: operations["GovernanceService_CreateIndicator"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/governance/indicators/{indicator}/samples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GovernanceService_ListIndicatorSamples"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/governance/indicators/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GovernanceService_GetIndicator"];
        put?: never;
        post?: never;
        delete: operations["GovernanceService_DeleteIndicator"];
        options?: never;
        head?: never;
        patch: operations["GovernanceService_UpdateIndicator"];
        trace?: never;
    };
    "/v1/governance/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GovernanceService_ListPolicies"];
        put?: never;
        post: operations["GovernanceService_CreatePolicy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/governance/policies:dryRun": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["GovernanceService_DryRunPolicy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/governance/policies/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GovernanceService_GetPolicy"];
        put?: never;
        post?: never;
        delete: operations["GovernanceService_DeletePolicy"];
        options?: never;
        head?: never;
        patch: operations["GovernanceService_UpdatePolicy"];
        trace?: never;
    };
    "/v1/governance/policies/{name}/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GovernanceService_ListPolicyActions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/kafka/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AgentService_ListAgents"];
        put?: never;
        post: operations["AgentService_CreateAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/kafka/agents/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AgentService_GetAgent"];
        put?: never;
        post?: never;
        delete: operations["AgentService_DeleteAgent"];
        options?: never;
        head?: never;
        patch: operations["AgentService_UpdateAgent"];
        trace?: never;
    };
    "/v1/kafka/agents/{name}:pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AgentService_PauseAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/kafka/agents/{name}:resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AgentService_ResumeAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/kafka/agents/{name}:rotateToken": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AgentService_RotateAgentToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/kafka/clusters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["KafkaClusterService_ListKafkaClusters"];
        put?: never;
        post: operations["KafkaClusterService_CreateKafkaCluster"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/kafka/clusters/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["KafkaClusterService_GetKafkaCluster"];
        put?: never;
        post?: never;
        delete: operations["KafkaClusterService_DeleteKafkaCluster"];
        options?: never;
        head?: never;
        patch: operations["KafkaClusterService_UpdateKafkaCluster"];
        trace?: never;
    };
    "/v1/kafka/clusters/{name}:pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["KafkaClusterService_PauseKafkaCluster"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/kafka/clusters/{name}:resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["KafkaClusterService_ResumeKafkaCluster"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/kafka/clusters/{name}/provider-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["KafkaClusterService_ListClusterProviderEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/kafka/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["KafkaTopicService_ListKafkaTopics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/kafka/topics/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["KafkaTopicService_GetKafkaTopic"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/kafka/topics/{name}:setConsumption": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["KafkaTopicService_SetConsumption"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AgentServiceUpdateAgentBody: {
            labels?: {
                [key: string]: string;
            };
            type?: components["schemas"]["v1AgentType"];
            /** @description Fields to update; unset fields are left unchanged. */
            updateMask?: string;
        };
        AsyncChannelServiceUpdateAsyncChannelBody: {
            labels?: {
                [key: string]: string;
            };
            /**
             * @description Fields to update; unset fields are left unchanged. `type` is immutable, the
             *     access policy is changed via SetAccessPolicy, and `channel_partitions` is
             *     changed via the staged re-shard flow (003.11) — none may appear in the mask.
             */
            updateMask?: string;
        };
        ClientServiceUpdateClientBody: {
            labels?: {
                [key: string]: string;
            };
            /** @description Fields to update; unset fields are left unchanged. */
            updateMask?: string;
        };
        DryRunPolicyResponseMatch: {
            indicatorValue?: string;
            resourceFrn?: string;
            wouldTrigger?: boolean;
        };
        GovernanceServiceUpdateIndicatorBody: {
            sourceAgents?: string[];
            stalenessThreshold?: string;
            unit?: string;
            /** @description Fields to update; unset fields are left unchanged. `applies_to` is immutable. */
            updateMask?: string;
        };
        GovernanceServiceUpdatePolicyBody: {
            actions?: components["schemas"]["v1Action"][];
            enabled?: boolean;
            indicator?: string;
            limit?: components["schemas"]["v1Limit"];
            matcher?: components["schemas"]["v1Matcher"];
            /** @description Fields to update; unset fields are left unchanged. */
            updateMask?: string;
            /** Format: int32 */
            weight?: number;
        };
        KafkaClusterServiceUpdateKafkaClusterBody: {
            clusterConfiguration?: {
                [key: string]: string;
            };
            clusterProviderAgent?: string;
            connectionStrings?: components["schemas"]["v1ConnectionString"][];
            labels?: {
                [key: string]: string;
            };
            /** @description Fields to update; unset fields are left unchanged. */
            updateMask?: string;
        };
        KafkaTopicServiceSetConsumptionBody: {
            consumption?: components["schemas"]["v1Consumption"];
        };
        protobufAny: {
            "@type"?: string;
        } & {
            [key: string]: unknown;
        };
        rpcStatus: {
            /** Format: int32 */
            code?: number;
            details?: components["schemas"]["protobufAny"][];
            message?: string;
        };
        /**
         * @description One access-policy document per channel. Evaluation for a (client, action):
         *     take the statements whose principal matches the client and whose permissions
         *     include the action; if any is EFFECT_DENY the action is denied; otherwise if
         *     any is EFFECT_ALLOW it is allowed; otherwise denied (zero trust).
         */
        v1AccessPolicy: {
            statements?: components["schemas"]["v1AccessPolicyStatement"][];
        };
        v1AccessPolicyStatement: {
            effect?: components["schemas"]["v1Effect"];
            /** @description One or more of PERMISSION_READ / PERMISSION_WRITE. Must be non-empty. */
            permissions?: components["schemas"]["v1Permission"][];
            principal?: components["schemas"]["v1Principal"];
        };
        v1Action: {
            /**
             * add_label      -> [key, value]
             *     remove_label   -> [key]
             *     set_status     -> [status]
             *     update_field   -> [field, value]
             *     increase_field_by / decrease_field_by -> [field, amount]
             */
            args?: string[];
            kind?: components["schemas"]["v1ActionKind"];
        };
        /**
         * @default ACTION_KIND_UNSPECIFIED
         * @enum {string}
         */
        v1ActionKind: "ACTION_KIND_UNSPECIFIED" | "ACTION_KIND_ADD_LABEL" | "ACTION_KIND_SET_STATUS" | "ACTION_KIND_UPDATE_FIELD" | "ACTION_KIND_INCREASE_FIELD_BY" | "ACTION_KIND_DECREASE_FIELD_BY" | "ACTION_KIND_REMOVE_LABEL";
        /**
         * @description An agent is a program registered with Franz that connects to the fleet API
         *     over gRPC, pulls work, and reports results. Franz never calls an agent.
         */
        v1Agent: {
            /** Format: date-time */
            createdAt?: string;
            /** @description Assigned by Franz. */
            frn?: string;
            /**
             * @description Arbitrary metadata labels — for information and as an extension point
             *     (owner, team, environment, future scoping rules, …).
             */
            labels?: {
                [key: string]: string;
            };
            name?: string;
            status?: components["schemas"]["v1AgentStatus"];
            type?: components["schemas"]["v1AgentType"];
            /** Format: date-time */
            updatedAt?: string;
        };
        /**
         * @description - AGENT_STATUS_ACTIVE: Registered and eligible to receive work.
         *      - AGENT_STATUS_PAUSED: Registered but Franz hands it no work.
         *      - AGENT_STATUS_DELETED: Soft-deleted. Terminal; the record is retained for audit.
         * @default AGENT_STATUS_UNSPECIFIED
         * @enum {string}
         */
        v1AgentStatus: "AGENT_STATUS_UNSPECIFIED" | "AGENT_STATUS_ACTIVE" | "AGENT_STATUS_PAUSED" | "AGENT_STATUS_DELETED";
        /**
         * @description - AGENT_TYPE_CLUSTER_PROVIDER: Deploys and maintains a substrate (Kafka cluster, RabbitMQ, ...).
         *      - AGENT_TYPE_RESOURCE_PROVIDER: Realises individual resources (Kafka topics, queues). Gregor Samsa is one.
         *      - AGENT_TYPE_TELEMETRY_AGENT: Publishes indicator and consumer-group telemetry. Odradek is one.
         * @default AGENT_TYPE_UNSPECIFIED
         * @enum {string}
         */
        v1AgentType: "AGENT_TYPE_UNSPECIFIED" | "AGENT_TYPE_CLUSTER_PROVIDER" | "AGENT_TYPE_RESOURCE_PROVIDER" | "AGENT_TYPE_TELEMETRY_AGENT" | "AGENT_TYPE_CUSTOM";
        /**
         * @description An Async Channel is the customer-facing boundary of asynchronous
         *     communication. Creating one causes Franz to generate one or more linked
         *     Kafka Topics (see kafka.proto). Formerly "Topic Definition".
         */
        v1AsyncChannel: {
            accessPolicy?: components["schemas"]["v1AccessPolicy"];
            /**
             * Format: int32
             * @description Shard count: Franz splits the channel into this many Kafka Topics, named
             *     "<name>-<index>" (index 0..channel_partitions-1). Changing it is a staged
             *     re-shard operation (003.4 / 003.11), not a plain field write.
             */
            channelPartitions?: number;
            /** Format: date-time */
            createdAt?: string;
            /** @description Assigned by Franz. */
            frn?: string;
            /** @description Arbitrary metadata labels for this channel. */
            labels?: {
                [key: string]: string;
            };
            /**
             * @description Unique name, provided at creation. Also the base name Franz uses to
             *     generate Kafka topic names.
             */
            name?: string;
            state?: components["schemas"]["v1ChannelState"];
            type?: components["schemas"]["v1ChannelType"];
            /** Format: date-time */
            updatedAt?: string;
        };
        /** @description The permission a specific client has on a channel, after evaluating the policy. */
        v1ChannelClientAccess: {
            clientFrn?: string;
            clientLabels?: {
                [key: string]: string;
            };
            effective?: components["schemas"]["v1Permission"][];
            /** @description Human-readable note on which statement matched. */
            matchedBy?: string;
        };
        /**
         * @description - CHANNEL_STATE_ACTIVE: Franz maintains the channel and its shards automatically.
         *      - CHANNEL_STATE_PAUSED: Recorded, but Franz has stopped reconciling the channel's shards.
         *      - CHANNEL_STATE_DELETED: Soft-deleted; agents remove the real-world resources.
         * @default CHANNEL_STATE_UNSPECIFIED
         * @enum {string}
         */
        v1ChannelState: "CHANNEL_STATE_UNSPECIFIED" | "CHANNEL_STATE_ACTIVE" | "CHANNEL_STATE_PAUSED" | "CHANNEL_STATE_DELETED";
        /**
         * @default CHANNEL_TYPE_UNSPECIFIED
         * @enum {string}
         */
        v1ChannelType: "CHANNEL_TYPE_UNSPECIFIED" | "CHANNEL_TYPE_KAFKA_TOPIC";
        /**
         * @description A fleet-wide identity that reads from or writes to Async Channels through the
         *     Franz SDK. A client has no Read/Write role of its own; every permission comes
         *     from the access policy of the channel it connects to.
         */
        v1Client: {
            /** Format: date-time */
            createdAt?: string;
            /** @description Assigned by Franz. */
            frn?: string;
            /** @description At least org.com/owner. Channel access policies match against these. */
            labels?: {
                [key: string]: string;
            };
            /** @description Globally unique, provided at registration. Also the default consumer-group prefix. */
            name?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        /**
         * @description A channel this client may use, and the permission granted. Derived from
         *     every channel access policy whose statements match the client.
         */
        v1ClientChannelAccess: {
            asyncChannel?: string;
            effective?: components["schemas"]["v1Permission"][];
            matchedBy?: string;
        };
        /** @description One provider status report, retained as history. */
        v1ClusterProviderEvent: {
            clusterFrn?: string;
            message?: string;
            /** Format: date-time */
            occurredAt?: string;
            phase?: components["schemas"]["v1ClusterProviderPhase"];
            reachable?: boolean;
            recipeRef?: string;
            reportingAgent?: string;
        };
        /**
         * @description What a Cluster Provider agent reports about a cluster it provisions.
         *     This is agent-observed reality — distinct from KafkaClusterState (operator
         *     intent). See 004-local-kafka-docker-agent.
         * @default CLUSTER_PROVIDER_PHASE_UNSPECIFIED
         * @enum {string}
         */
        v1ClusterProviderPhase: "CLUSTER_PROVIDER_PHASE_UNSPECIFIED" | "CLUSTER_PROVIDER_PHASE_PROVISIONING" | "CLUSTER_PROVIDER_PHASE_READY" | "CLUSTER_PROVIDER_PHASE_DEGRADED" | "CLUSTER_PROVIDER_PHASE_ERROR" | "CLUSTER_PROVIDER_PHASE_STOPPED" | "CLUSTER_PROVIDER_PHASE_REMOVED";
        /**
         * @description Current provider-reported status for a cluster: the latest
         *     cluster_provider_event. See 004-local-kafka-docker-agent.
         */
        v1ClusterProviderStatus: {
            message?: string;
            phase?: components["schemas"]["v1ClusterProviderPhase"];
            reachable?: boolean;
            recipeRef?: string;
            /** Format: date-time */
            reportedAt?: string;
            reportingAgent?: string;
        };
        /**
         * @description A way to reach a cluster's brokers. Today only PLAINTEXT is supported; the
         *     message exists so authenticated connection types can be added later.
         */
        v1ConnectionString: {
            bootstrapUrls?: string[];
            type?: components["schemas"]["v1ConnectionType"];
        };
        /**
         * @default CONNECTION_TYPE_UNSPECIFIED
         * @enum {string}
         */
        v1ConnectionType: "CONNECTION_TYPE_UNSPECIFIED" | "CONNECTION_TYPE_PLAINTEXT";
        /**
         * @default CONSUMPTION_UNSPECIFIED
         * @enum {string}
         */
        v1Consumption: "CONSUMPTION_UNSPECIFIED" | "CONSUMPTION_ENABLED" | "CONSUMPTION_DISABLED";
        v1CreateAgentRequest: {
            labels?: {
                [key: string]: string;
            };
            name?: string;
            type?: components["schemas"]["v1AgentType"];
        };
        v1CreateAgentResponse: {
            agent?: components["schemas"]["v1Agent"];
            /**
             * @description Bearer token the agent presents to authenticate (gRPC `authorization`
             *     metadata). Returned once, on creation; Franz stores only its hash.
             *     See 004-local-kafka-docker-agent.
             */
            token?: string;
        };
        v1CreateAsyncChannelRequest: {
            accessPolicy?: components["schemas"]["v1AccessPolicy"];
            /** Format: int32 */
            channelPartitions?: number;
            labels?: {
                [key: string]: string;
            };
            name?: string;
            type?: components["schemas"]["v1ChannelType"];
        };
        v1CreateAsyncChannelResponse: {
            asyncChannel?: components["schemas"]["v1AsyncChannel"];
        };
        v1CreateClientRequest: {
            labels?: {
                [key: string]: string;
            };
            name?: string;
        };
        v1CreateClientResponse: {
            client?: components["schemas"]["v1Client"];
        };
        v1CreateIndicatorRequest: {
            appliesTo?: components["schemas"]["v1Entity"];
            name?: string;
            sourceAgents?: string[];
            stalenessThreshold?: string;
            unit?: string;
        };
        v1CreateIndicatorResponse: {
            indicator?: components["schemas"]["v1Indicator"];
        };
        /**
         * @description Only the client-settable fields of a KafkaCluster. Franz assigns the FRN and
         *     the timestamps.
         */
        v1CreateKafkaClusterRequest: {
            clusterConfiguration?: {
                [key: string]: string;
            };
            clusterProviderAgent?: string;
            connectionStrings?: components["schemas"]["v1ConnectionString"][];
            labels?: {
                [key: string]: string;
            };
            name?: string;
        };
        v1CreateKafkaClusterResponse: {
            kafkaCluster?: components["schemas"]["v1KafkaCluster"];
        };
        v1CreatePolicyRequest: {
            actions?: components["schemas"]["v1Action"][];
            enabled?: boolean;
            indicator?: string;
            limit?: components["schemas"]["v1Limit"];
            matcher?: components["schemas"]["v1Matcher"];
            name?: string;
            /** Format: int32 */
            weight?: number;
        };
        v1CreatePolicyResponse: {
            policy?: components["schemas"]["v1Policy"];
        };
        v1DeleteAgentResponse: Record<string, never>;
        v1DeleteAsyncChannelResponse: Record<string, never>;
        v1DeleteClientResponse: Record<string, never>;
        v1DeleteIndicatorResponse: Record<string, never>;
        v1DeleteKafkaClusterResponse: Record<string, never>;
        v1DeletePolicyResponse: Record<string, never>;
        v1DryRunPolicyRequest: {
            actions?: components["schemas"]["v1Action"][];
            /**
             * @description The policy definition to evaluate against the latest samples. `weight` and
             *     `enabled` do not affect a dry run and are omitted.
             */
            indicator?: string;
            limit?: components["schemas"]["v1Limit"];
            matcher?: components["schemas"]["v1Matcher"];
        };
        v1DryRunPolicyResponse: {
            matches?: components["schemas"]["DryRunPolicyResponseMatch"][];
        };
        /**
         * @default EFFECT_UNSPECIFIED
         * @enum {string}
         */
        v1Effect: "EFFECT_UNSPECIFIED" | "EFFECT_ALLOW" | "EFFECT_DENY";
        /**
         * @default ENTITY_UNSPECIFIED
         * @enum {string}
         */
        v1Entity: "ENTITY_UNSPECIFIED" | "ENTITY_ASYNC_CHANNEL" | "ENTITY_KAFKA_TOPIC" | "ENTITY_KAFKA_CLUSTER";
        v1GetAgentResponse: {
            agent?: components["schemas"]["v1Agent"];
        };
        v1GetAsyncChannelResponse: {
            asyncChannel?: components["schemas"]["v1AsyncChannel"];
        };
        v1GetClientResponse: {
            client?: components["schemas"]["v1Client"];
        };
        v1GetIndicatorResponse: {
            indicator?: components["schemas"]["v1Indicator"];
        };
        v1GetKafkaClusterResponse: {
            kafkaCluster?: components["schemas"]["v1KafkaCluster"];
        };
        v1GetKafkaTopicResponse: {
            kafkaTopic?: components["schemas"]["v1KafkaTopic"];
        };
        v1GetPolicyResponse: {
            policy?: components["schemas"]["v1Policy"];
        };
        /**
         * @description An indicator that Telemetry Agents publish samples for and policies read.
         *     Admin-created (CreateIndicator); a sample or policy for an unknown indicator
         *     is rejected. See 003.14-telemetry-ingest.md.
         */
        v1Indicator: {
            appliesTo?: components["schemas"]["v1Entity"];
            health?: components["schemas"]["v1IndicatorHealth"];
            /** Format: date-time */
            lastSampleAt?: string;
            name?: string;
            sourceAgents?: string[];
            /** @description Beyond this age the indicator is stale and policies reading it do not act. */
            stalenessThreshold?: string;
            /** @description "bytes", "count", "duration", "boolean", ... */
            unit?: string;
        };
        /**
         * @default INDICATOR_HEALTH_UNSPECIFIED
         * @enum {string}
         */
        v1IndicatorHealth: "INDICATOR_HEALTH_UNSPECIFIED" | "INDICATOR_HEALTH_HEALTHY" | "INDICATOR_HEALTH_STALE";
        /**
         * @description One stored indicator sample, returned by ListIndicatorSamples. The write-side
         *     shape is telemetry.proto's IndicatorSample.
         */
        v1IndicatorSampleView: {
            resourceEntity?: components["schemas"]["v1Entity"];
            resourceFrn?: string;
            /** Format: date-time */
            sampleAt?: string;
            value?: string;
        };
        /**
         * @description A Kafka Cluster registration. Franz records where a cluster lives and its
         *     fleet context; it never connects to the cluster. Real-world work is done by
         *     the linked Cluster Provider agent (if any) and by Resource Provider agents.
         */
        v1KafkaCluster: {
            /**
             * @description Default Kafka configuration applied to topics on this cluster when nothing
             *     more specific is declared (e.g. "default.replication.factor" -> "3").
             */
            clusterConfiguration?: {
                [key: string]: string;
            };
            /**
             * @description Optional name of the Cluster Provider agent that deploys and maintains this
             *     cluster's substrate. Empty means the infrastructure is managed outside Franz.
             */
            clusterProviderAgent?: string;
            /**
             * @description How to reach the cluster's brokers. Repeated so additional connection
             *     types (each with their own auth) can be added without a breaking change.
             */
            connectionStrings?: components["schemas"]["v1ConnectionString"][];
            /** Format: date-time */
            createdAt?: string;
            /** @description Assigned by Franz. */
            frn?: string;
            /** @description Fleet context. Source of truth for placement matching. */
            labels?: {
                [key: string]: string;
            };
            /** @description Control-plane identifier, provided at registration. Immutable. */
            name?: string;
            providerStatus?: components["schemas"]["v1ClusterProviderStatus"];
            state?: components["schemas"]["v1KafkaClusterState"];
            /** Format: date-time */
            updatedAt?: string;
        };
        /**
         * @description - KAFKA_CLUSTER_STATE_ACTIVE: Registered and eligible for placement.
         *      - KAFKA_CLUSTER_STATE_PAUSED: Registered but excluded from new placement; existing topics are untouched.
         *      - KAFKA_CLUSTER_STATE_DELETED: Soft-deleted. Terminal; the record is retained for audit.
         * @default KAFKA_CLUSTER_STATE_UNSPECIFIED
         * @enum {string}
         */
        v1KafkaClusterState: "KAFKA_CLUSTER_STATE_UNSPECIFIED" | "KAFKA_CLUSTER_STATE_ACTIVE" | "KAFKA_CLUSTER_STATE_PAUSED" | "KAFKA_CLUSTER_STATE_DELETED";
        /**
         * @description A Kafka Topic is one generated topic of an Async Channel, placed on one
         *     Kafka Cluster. It tracks reconciliation with the real topic. Formerly
         *     "Topic Claim". Franz creates and deletes these; clients do not — every field
         *     here is set by Franz. Consumption is changed through SetConsumption.
         */
        v1KafkaTopic: {
            /** @description Owning Async Channel. */
            asyncChannel?: string;
            consumption?: components["schemas"]["v1Consumption"];
            /** Format: date-time */
            createdAt?: string;
            frn?: string;
            /**
             * Format: int64
             * @description Bumped whenever Franz changes this topic's desired state. Agents echo it
             *     when reporting work so Franz can reject stale reports.
             */
            generation?: string;
            /** @description Cluster this topic is placed on. */
            kafkaCluster?: string;
            /** @description Franz-generated Kafka topic name (also the real name in the cluster). */
            name?: string;
            /**
             * Format: int32
             * @description Desired Kafka partition count for the real topic. May only increase.
             */
            partitions?: number;
            /**
             * Format: int32
             * @description Desired replication factor for the real topic.
             */
            replicationFactor?: number;
            state?: components["schemas"]["v1KafkaTopicState"];
            /**
             * @description Per-topic Kafka configuration (retention, cleanup policy, ...). Keys set here
             *     win over the cluster configuration in the merge. Does NOT carry partition
             *     count or replication factor — those are the dedicated fields below.
             */
            topicConfiguration?: {
                [key: string]: string;
            };
            trafficShare?: components["schemas"]["v1TrafficShare"];
            /** Format: date-time */
            updatedAt?: string;
        };
        /**
         * @default KAFKA_TOPIC_STATE_UNSPECIFIED
         * @enum {string}
         */
        v1KafkaTopicState: "KAFKA_TOPIC_STATE_UNSPECIFIED" | "KAFKA_TOPIC_STATE_PENDING" | "KAFKA_TOPIC_STATE_READY" | "KAFKA_TOPIC_STATE_PAUSED" | "KAFKA_TOPIC_STATE_ERROR" | "KAFKA_TOPIC_STATE_DELETED";
        v1Limit: {
            operator?: components["schemas"]["v1Operator"];
            /**
             * @description Compared against the latest indicator sample. Encoding follows the
             *     indicator's unit (e.g. "150Gi", "3", "90d").
             */
            value?: string;
        };
        v1ListAgentsResponse: {
            agents?: components["schemas"]["v1Agent"][];
            page?: components["schemas"]["v1PageResponse"];
        };
        v1ListAsyncChannelsResponse: {
            asyncChannels?: components["schemas"]["v1AsyncChannel"][];
            page?: components["schemas"]["v1PageResponse"];
        };
        v1ListChannelClientsResponse: {
            clients?: components["schemas"]["v1ChannelClientAccess"][];
            page?: components["schemas"]["v1PageResponse"];
        };
        v1ListClientChannelAccessResponse: {
            access?: components["schemas"]["v1ClientChannelAccess"][];
            page?: components["schemas"]["v1PageResponse"];
        };
        v1ListClientsResponse: {
            clients?: components["schemas"]["v1Client"][];
            page?: components["schemas"]["v1PageResponse"];
        };
        v1ListClusterProviderEventsResponse: {
            events?: components["schemas"]["v1ClusterProviderEvent"][];
            page?: components["schemas"]["v1PageResponse"];
        };
        v1ListConsumerGroupObservationsResponse: {
            observations?: components["schemas"]["v1ObservedConsumerGroup"][];
            page?: components["schemas"]["v1PageResponse"];
        };
        v1ListIndicatorSamplesResponse: {
            page?: components["schemas"]["v1PageResponse"];
            samples?: components["schemas"]["v1IndicatorSampleView"][];
        };
        v1ListIndicatorsResponse: {
            indicators?: components["schemas"]["v1Indicator"][];
            page?: components["schemas"]["v1PageResponse"];
        };
        v1ListKafkaClustersResponse: {
            kafkaClusters?: components["schemas"]["v1KafkaCluster"][];
            page?: components["schemas"]["v1PageResponse"];
        };
        v1ListKafkaTopicsResponse: {
            kafkaTopics?: components["schemas"]["v1KafkaTopic"][];
            page?: components["schemas"]["v1PageResponse"];
        };
        v1ListObservedConsumerGroupsResponse: {
            groups?: components["schemas"]["v1ObservedConsumerGroup"][];
            page?: components["schemas"]["v1PageResponse"];
        };
        v1ListPoliciesResponse: {
            page?: components["schemas"]["v1PageResponse"];
            policies?: components["schemas"]["v1Policy"][];
        };
        v1ListPolicyActionsResponse: {
            actions?: components["schemas"]["v1PolicyAction"][];
            page?: components["schemas"]["v1PageResponse"];
        };
        v1Matcher: {
            entity?: components["schemas"]["v1Entity"];
            /** @description Label selector. Empty means every resource of the entity kind. */
            selector?: string;
        };
        /**
         * @description A consumer group observed for this client, reported by a Telemetry Agent.
         *     Not registered in Franz. ListObservedConsumerGroups returns the current view
         *     (one row per (group, topic), latest sighting); ListConsumerGroupObservations
         *     returns the raw sightings within a time range. See 003.14-telemetry-ingest.md.
         */
        v1ObservedConsumerGroup: {
            asyncChannel?: string;
            /** @description true when the group name is not the default <client>.<topic> form. */
            custom?: boolean;
            group?: string;
            kafkaTopic?: string;
            /**
             * Format: date-time
             * @description Current view: most recent sighting. History view: the sighting's time.
             */
            lastSeenAt?: string;
            reportedByAgent?: string;
        };
        /**
         * @default OPERATOR_UNSPECIFIED
         * @enum {string}
         */
        v1Operator: "OPERATOR_UNSPECIFIED" | "OPERATOR_LESS_THAN" | "OPERATOR_LESS_THAN_OR_EQUAL" | "OPERATOR_EQUAL" | "OPERATOR_NOT_EQUAL" | "OPERATOR_GREATER_THAN_OR_EQUAL" | "OPERATOR_GREATER_THAN";
        /** @description Standard pagination request fields. Embed in every List request. */
        v1PageRequest: {
            /**
             * Format: int32
             * @description Maximum number of items to return. The server may return fewer.
             */
            pageSize?: number;
            /** @description Opaque token from a previous response's next_page_token. Empty for the first page. */
            pageToken?: string;
        };
        /** @description Standard pagination response fields. Embed in every List response. */
        v1PageResponse: {
            /** @description Pass as PageRequest.page_token to fetch the next page. Empty when there are no more. */
            nextPageToken?: string;
            /**
             * Format: int32
             * @description Total number of items across all pages, when the server can compute it cheaply.
             */
            totalSize?: number;
        };
        v1PauseAgentResponse: {
            agent?: components["schemas"]["v1Agent"];
        };
        v1PauseAsyncChannelResponse: {
            asyncChannel?: components["schemas"]["v1AsyncChannel"];
        };
        v1PauseKafkaClusterResponse: {
            kafkaCluster?: components["schemas"]["v1KafkaCluster"];
        };
        /**
         * @description A permission that a channel access policy statement grants to a client.
         * @default PERMISSION_UNSPECIFIED
         * @enum {string}
         */
        v1Permission: "PERMISSION_UNSPECIFIED" | "PERMISSION_READ" | "PERMISSION_WRITE";
        /**
         * @description A governance policy watches one indicator and acts on the resources it
         *     matches when a limit is crossed. Reactive only: actions change Franz's
         *     declared state, which the normal reconciliation path realises.
         */
        v1Policy: {
            actions?: components["schemas"]["v1Action"][];
            /** Format: date-time */
            createdAt?: string;
            enabled?: boolean;
            /** @description Assigned by Franz. */
            frn?: string;
            /** @description Indicator name published by a Telemetry Agent. */
            indicator?: string;
            /** Format: date-time */
            lastFiredAt?: string;
            limit?: components["schemas"]["v1Limit"];
            matcher?: components["schemas"]["v1Matcher"];
            name?: string;
            /** Format: date-time */
            updatedAt?: string;
            /**
             * Format: int32
             * @description Breaks ties when several policies act on the same resource. Higher wins.
             */
            weight?: number;
        };
        /** @description One automated change a policy made. */
        v1PolicyAction: {
            action?: components["schemas"]["v1Action"];
            indicatorValue?: string;
            /** Format: date-time */
            occurredAt?: string;
            resourceFrn?: string;
            /** @description Resulting revision or a note. */
            result?: string;
        };
        /**
         * @description A statement matches a client when its FRN matches client_frn (if set) OR its
         *     labels satisfy the selector (if set); at least one must be set. Both
         *     client_frn and the label-selector values accept `*` as a wildcard.
         */
        v1Principal: {
            clientFrn?: string;
            labels?: string;
        };
        v1ResumeAgentResponse: {
            agent?: components["schemas"]["v1Agent"];
        };
        v1ResumeAsyncChannelResponse: {
            asyncChannel?: components["schemas"]["v1AsyncChannel"];
        };
        v1ResumeKafkaClusterResponse: {
            kafkaCluster?: components["schemas"]["v1KafkaCluster"];
        };
        v1RotateAgentTokenResponse: {
            /** @description The new bearer token. The previous token is invalidated immediately. */
            token?: string;
        };
        v1SetAccessPolicyResponse: {
            asyncChannel?: components["schemas"]["v1AsyncChannel"];
        };
        v1SetConsumptionResponse: {
            kafkaTopic?: components["schemas"]["v1KafkaTopic"];
        };
        /** @description A proportion of channel traffic, e.g. value 45, unit "percent". */
        v1TrafficShare: {
            unit?: string;
            /** Format: double */
            value?: number;
        };
        v1UpdateAgentResponse: {
            agent?: components["schemas"]["v1Agent"];
        };
        v1UpdateAsyncChannelResponse: {
            asyncChannel?: components["schemas"]["v1AsyncChannel"];
        };
        v1UpdateClientResponse: {
            client?: components["schemas"]["v1Client"];
        };
        v1UpdateIndicatorResponse: {
            indicator?: components["schemas"]["v1Indicator"];
        };
        v1UpdateKafkaClusterResponse: {
            kafkaCluster?: components["schemas"]["v1KafkaCluster"];
        };
        v1UpdatePolicyResponse: {
            policy?: components["schemas"]["v1Policy"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AsyncChannelService_ListAsyncChannels: {
        parameters: {
            query?: {
                /** @description Maximum number of items to return. The server may return fewer. */
                "page.pageSize"?: number;
                /** @description Opaque token from a previous response's next_page_token. Empty for the first page. */
                "page.pageToken"?: string;
                selector?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1ListAsyncChannelsResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AsyncChannelService_CreateAsyncChannel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["v1CreateAsyncChannelRequest"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1CreateAsyncChannelResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AsyncChannelService_GetAsyncChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1GetAsyncChannelResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AsyncChannelService_DeleteAsyncChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1DeleteAsyncChannelResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AsyncChannelService_UpdateAsyncChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AsyncChannelServiceUpdateAsyncChannelBody"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1UpdateAsyncChannelResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AsyncChannelService_PauseAsyncChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1PauseAsyncChannelResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AsyncChannelService_ResumeAsyncChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1ResumeAsyncChannelResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AsyncChannelService_SetAccessPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["v1AccessPolicy"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1SetAccessPolicyResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AsyncChannelService_ListChannelClients: {
        parameters: {
            query?: {
                /** @description Maximum number of items to return. The server may return fewer. */
                "page.pageSize"?: number;
                /** @description Opaque token from a previous response's next_page_token. Empty for the first page. */
                "page.pageToken"?: string;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1ListChannelClientsResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    ClientService_ListClients: {
        parameters: {
            query?: {
                /** @description Maximum number of items to return. The server may return fewer. */
                "page.pageSize"?: number;
                /** @description Opaque token from a previous response's next_page_token. Empty for the first page. */
                "page.pageToken"?: string;
                selector?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1ListClientsResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    ClientService_CreateClient: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["v1CreateClientRequest"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1CreateClientResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    ClientService_GetClient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1GetClientResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    ClientService_DeleteClient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1DeleteClientResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    ClientService_UpdateClient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientServiceUpdateClientBody"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1UpdateClientResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    ClientService_ListClientChannelAccess: {
        parameters: {
            query?: {
                /** @description Maximum number of items to return. The server may return fewer. */
                "page.pageSize"?: number;
                /** @description Opaque token from a previous response's next_page_token. Empty for the first page. */
                "page.pageToken"?: string;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1ListClientChannelAccessResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    ClientService_ListConsumerGroupObservations: {
        parameters: {
            query?: {
                from?: string;
                /** @description Maximum number of items to return. The server may return fewer. */
                "page.pageSize"?: number;
                /** @description Opaque token from a previous response's next_page_token. Empty for the first page. */
                "page.pageToken"?: string;
                to?: string;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1ListConsumerGroupObservationsResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    ClientService_ListObservedConsumerGroups: {
        parameters: {
            query?: {
                /** @description Maximum number of items to return. The server may return fewer. */
                "page.pageSize"?: number;
                /** @description Opaque token from a previous response's next_page_token. Empty for the first page. */
                "page.pageToken"?: string;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1ListObservedConsumerGroupsResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    GovernanceService_ListIndicators: {
        parameters: {
            query?: {
                /** @description Maximum number of items to return. The server may return fewer. */
                "page.pageSize"?: number;
                /** @description Opaque token from a previous response's next_page_token. Empty for the first page. */
                "page.pageToken"?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1ListIndicatorsResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    GovernanceService_CreateIndicator: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["v1CreateIndicatorRequest"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1CreateIndicatorResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    GovernanceService_ListIndicatorSamples: {
        parameters: {
            query?: {
                from?: string;
                /** @description Maximum number of items to return. The server may return fewer. */
                "page.pageSize"?: number;
                /** @description Opaque token from a previous response's next_page_token. Empty for the first page. */
                "page.pageToken"?: string;
                /** @description Optional: restrict to one resource. */
                resourceFrn?: string;
                to?: string;
            };
            header?: never;
            path: {
                indicator: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1ListIndicatorSamplesResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    GovernanceService_GetIndicator: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1GetIndicatorResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    GovernanceService_DeleteIndicator: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1DeleteIndicatorResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    GovernanceService_UpdateIndicator: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GovernanceServiceUpdateIndicatorBody"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1UpdateIndicatorResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    GovernanceService_ListPolicies: {
        parameters: {
            query?: {
                /** @description Maximum number of items to return. The server may return fewer. */
                "page.pageSize"?: number;
                /** @description Opaque token from a previous response's next_page_token. Empty for the first page. */
                "page.pageToken"?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1ListPoliciesResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    GovernanceService_CreatePolicy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["v1CreatePolicyRequest"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1CreatePolicyResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    GovernanceService_DryRunPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["v1DryRunPolicyRequest"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1DryRunPolicyResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    GovernanceService_GetPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1GetPolicyResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    GovernanceService_DeletePolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1DeletePolicyResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    GovernanceService_UpdatePolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GovernanceServiceUpdatePolicyBody"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1UpdatePolicyResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    GovernanceService_ListPolicyActions: {
        parameters: {
            query?: {
                /** @description Maximum number of items to return. The server may return fewer. */
                "page.pageSize"?: number;
                /** @description Opaque token from a previous response's next_page_token. Empty for the first page. */
                "page.pageToken"?: string;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1ListPolicyActionsResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AgentService_ListAgents: {
        parameters: {
            query?: {
                /** @description Maximum number of items to return. The server may return fewer. */
                "page.pageSize"?: number;
                /** @description Opaque token from a previous response's next_page_token. Empty for the first page. */
                "page.pageToken"?: string;
                /**
                 * @description Optional filter by type.
                 *
                 *      - AGENT_TYPE_CLUSTER_PROVIDER: Deploys and maintains a substrate (Kafka cluster, RabbitMQ, ...).
                 *      - AGENT_TYPE_RESOURCE_PROVIDER: Realises individual resources (Kafka topics, queues). Gregor Samsa is one.
                 *      - AGENT_TYPE_TELEMETRY_AGENT: Publishes indicator and consumer-group telemetry. Odradek is one.
                 */
                type?: "AGENT_TYPE_UNSPECIFIED" | "AGENT_TYPE_CLUSTER_PROVIDER" | "AGENT_TYPE_RESOURCE_PROVIDER" | "AGENT_TYPE_TELEMETRY_AGENT" | "AGENT_TYPE_CUSTOM";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1ListAgentsResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AgentService_CreateAgent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["v1CreateAgentRequest"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1CreateAgentResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AgentService_GetAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1GetAgentResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AgentService_DeleteAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1DeleteAgentResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AgentService_UpdateAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentServiceUpdateAgentBody"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1UpdateAgentResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AgentService_PauseAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1PauseAgentResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AgentService_ResumeAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1ResumeAgentResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    AgentService_RotateAgentToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1RotateAgentTokenResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    KafkaClusterService_ListKafkaClusters: {
        parameters: {
            query?: {
                /** @description Maximum number of items to return. The server may return fewer. */
                "page.pageSize"?: number;
                /** @description Opaque token from a previous response's next_page_token. Empty for the first page. */
                "page.pageToken"?: string;
                /** @description Optional label selector to filter the result. */
                selector?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1ListKafkaClustersResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    KafkaClusterService_CreateKafkaCluster: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Only the client-settable fields of a KafkaCluster. Franz assigns the FRN and
         *     the timestamps.
         */
        requestBody: {
            content: {
                "application/json": components["schemas"]["v1CreateKafkaClusterRequest"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1CreateKafkaClusterResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    KafkaClusterService_GetKafkaCluster: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1GetKafkaClusterResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    KafkaClusterService_DeleteKafkaCluster: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1DeleteKafkaClusterResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    KafkaClusterService_UpdateKafkaCluster: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KafkaClusterServiceUpdateKafkaClusterBody"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1UpdateKafkaClusterResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    KafkaClusterService_PauseKafkaCluster: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1PauseKafkaClusterResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    KafkaClusterService_ResumeKafkaCluster: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1ResumeKafkaClusterResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    KafkaClusterService_ListClusterProviderEvents: {
        parameters: {
            query?: {
                /** @description Maximum number of items to return. The server may return fewer. */
                "page.pageSize"?: number;
                /** @description Opaque token from a previous response's next_page_token. Empty for the first page. */
                "page.pageToken"?: string;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1ListClusterProviderEventsResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    KafkaTopicService_ListKafkaTopics: {
        parameters: {
            query?: {
                /** @description Filter to one channel. Optional. */
                asyncChannel?: string;
                /** @description Filter to one cluster. Optional. */
                kafkaCluster?: string;
                /** @description Maximum number of items to return. The server may return fewer. */
                "page.pageSize"?: number;
                /** @description Opaque token from a previous response's next_page_token. Empty for the first page. */
                "page.pageToken"?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1ListKafkaTopicsResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    KafkaTopicService_GetKafkaTopic: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1GetKafkaTopicResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
    KafkaTopicService_SetConsumption: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KafkaTopicServiceSetConsumptionBody"];
            };
        };
        responses: {
            /** @description A successful response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["v1SetConsumptionResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["rpcStatus"];
                };
            };
        };
    };
}
